### ISSUE TITLE
methods not working

### ISSUE THREAD

**Issue by thepixelmonk** [loopj/jquery-simple-slider#8]
when running `data.el.simpleSlider('setRatio', 1)` inside the ready callback, I get: `Uncaught TypeError: Cannot read property 'setRatio' of undefined`

**Comment by pratikabu** [comment]
I was facing this issue and I did as below.

I replaced `document.addEventListener('DOMContentLoaded', function () {})` with
`$( document ).ready(function() {})` and it started working fine.

Thanks for the clue.
